language: 
  - python

python:
  - '3.6'

cache: 
  - pip

install:
  - pip install mypy flake8 pydocstyle

script:
  - mypy 'Machine Learning/Project Digits/.' 
  - mypy 'Neural Networks/.'
  - mypy 'Deep Learning/.'

  - flake8 'Machine Learning/Project Digits/.' 
  - flake8 'Neural Networks/.'
  - flake8 'Deep Learning/.'

  - pydocstyle 'Machine Learning/Project Digits/.' 
  - pydocstyle 'Neural Networks/.'
  - pydocstyle 'Deep Learning/.'
