#!/bin/bash
#SBATCH --time=00:10:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --mem=64000

module load matplotlib
module load TensorFlow 
pip install --user tensorflow-datasets

srun ./plotall.sh
